export enum AppPage {
  auth = 'auth',
  renterHome = 'renterHome',
  renterCarDetail = 'renterCarDetail',
  renterCreateBooking = 'renterCreateBooking',
  renterDepositPayment = 'renterDepositPayment',
  renterTrips = 'renterTrips',
  renterBookingDetail = 'renterBookingDetail',
  renterReview = 'renterReview',
  profile = 'profile',
  ownerDashboard = 'ownerDashboard',
  ownerCars = 'ownerCars',
  ownerCreateCar = 'ownerCreateCar',
  ownerBookings = 'ownerBookings',
  ownerBookingDetail = 'ownerBookingDetail',
  adminDashboard = 'adminDashboard',
  adminPendingPayments = 'adminPendingPayments',
  adminRecentBookings = 'adminRecentBookings',
  adminUsers = 'adminUsers',
  adminCars = 'adminCars',
  adminRevenue = 'adminRevenue',
}
